### ISSUE TITLE
Build Your First Chatbot with SAP Conversational AI

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [SAPDocuments/sap-conversational-ai#335]
Tutorials: https://developers.sap.com/tutorials/cai-bot-getting-started.html
--------------------------

In Step 10, the text "Click on the bottom-right **_blue_** button Chat Preview and start sending messages." might need to be replaced with "Click on the bottom-right **_yellow_** button Chat Preview and start sending messages."
Because, the "Chat Preview" button is actually yellow in color.

**Comment by thecodester** [comment]
Yes, it is yellow. Glad someone is reading closely :-)

Fixed https://github.com/SAPDocuments/sap-conversational-ai/commit/829a652bb09f42b8e3ae9e8dab82a7a14376115c
