### ISSUE TITLE
Call SAP Conversational AI API Using OAuth

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [SAPDocuments/sap-conversational-ai#336]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-api-oauth.html
--------------------------

In Step 1: Create Python project, at the very end, there is this text "Your project should look like this:" and nothing else after it.
Maybe there is a screenshot missing.

**Comment by thecodester** [comment]
Added screenshot -- https://github.com/SAPDocuments/sap-conversational-ai/commit/829a652bb09f42b8e3ae9e8dab82a7a14376115c

Thanks for catching

**Comment by mohamedyosufdeenjmh** [comment]
You are welcome!
